name: push

run-name: Run tests with ${{ github.sha }} commit by {{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Install Pytorch
        run: |
          python -m pip install --upgrade pip
          pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      - name: Install est_models
        run: pip install .
      - name: Install dependencies
        run: |
          pip install transformers==4.36.2 diffusers==0.25.0 huggingface_hub==0.20.1 controlnet-aux==0.0.7 accelerate==0.25.0
          pip install omegaconf==2.3.0 opencv-python==4.8.0.74 pillow pytest
      - name: Run Pytest
        run: pytest tests/test_pipeline_cpu.py
